# Generated by Django 5.2.16 on 2026-07-14 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente a partir del nombre. Ejemplo: puertas-y-accesos.', max_length=140, unique=True, verbose_name='identificador URL')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('icon_key', models.CharField(blank=True, help_text='Ejemplo: door, security, electricity o printer-3d.', max_length=50, verbose_name='nombre interno del icono')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Los números menores aparecen primero.', verbose_name='orden de presentación')),
                ('is_active', models.BooleanField(default=True, verbose_name='categoría activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'categoría de servicio',
                'verbose_name_plural': 'categorías de servicios',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente. Ejemplo: automatizacion-de-portones.', max_length=180, unique=True, verbose_name='identificador URL')),
                ('card_description', models.CharField(help_text='Texto breve que aparecerá en listados y tarjetas.', max_length=260, verbose_name='descripción para tarjetas')),
                ('introduction', models.TextField(blank=True, help_text='Descripción amplia que utilizaremos en la página individual del servicio.', verbose_name='introducción del servicio')),
                ('icon_key', models.CharField(blank=True, max_length=50, verbose_name='nombre interno del icono')),
                ('whatsapp_message', models.CharField(blank=True, help_text='Mensaje que se preparará al consultar este servicio.', max_length=400, verbose_name='mensaje inicial de WhatsApp')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='título SEO')),
                ('seo_description', models.CharField(blank=True, max_length=170, verbose_name='descripción SEO')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Los números menores aparecen primero.', verbose_name='orden de presentación')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mostrar como destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='servicio activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ('category__display_order', 'display_order', 'name'),
            },
        ),
    ]
