# Generated by Django 5.2.16 on 2026-07-14 22:24

import apps.services.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden de presentación')),
                ('is_active', models.BooleanField(default=True, verbose_name='beneficio activo')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='services.service', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'beneficio',
                'verbose_name_plural': 'beneficios',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240, verbose_name='pregunta')),
                ('answer', models.TextField(verbose_name='respuesta')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden de presentación')),
                ('is_active', models.BooleanField(default=True, verbose_name='pregunta activa')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'pregunta frecuente',
                'verbose_name_plural': 'preguntas frecuentes',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='característica')),
                ('description', models.CharField(max_length=300, verbose_name='detalle')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden de presentación')),
                ('is_active', models.BooleanField(default=True, verbose_name='característica activa')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'característica',
                'verbose_name_plural': 'características',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.services.models.service_image_upload_path, verbose_name='archivo de imagen')),
                ('alt_text', models.CharField(help_text='Describe brevemente lo que aparece en la imagen. Ejemplo: Portón corredizo automatizado en Huancayo.', max_length=180, verbose_name='texto alternativo')),
                ('caption', models.CharField(blank=True, max_length=220, verbose_name='descripción visible')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden de presentación')),
                ('is_cover', models.BooleanField(default=False, verbose_name='usar como imagen principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='imagen activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'imagen del servicio',
                'verbose_name_plural': 'imágenes del servicio',
                'ordering': ('-is_cover', 'display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='nombre de la etapa')),
                ('description', models.TextField(verbose_name='descripción')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden de presentación')),
                ('is_active', models.BooleanField(default=True, verbose_name='etapa activa')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='services.service', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'etapa del proceso',
                'verbose_name_plural': 'etapas del proceso',
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
