# Generated by Django 5.2.16 on 2026-07-14 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(default='MS Electrical', max_length=120, verbose_name='nombre comercial')),
                ('legal_name', models.CharField(default='MS Electrical', help_text='Este dato deberá reemplazarse si la razón social legal es diferente al nombre comercial.', max_length=180, verbose_name='razón social')),
                ('ruc', models.CharField(default='10754525636', max_length=11, validators=[django.core.validators.RegexValidator(message='El RUC debe contener exactamente 11 números.', regex='^\\d{11}$')], verbose_name='RUC')),
                ('responsible_name', models.CharField(default='Pool Diego Medina Socualaya', max_length=180, verbose_name='responsable')),
                ('tagline', models.CharField(default='Seguridad, tecnología y diseño en cada acceso.', max_length=180, verbose_name='eslogan')),
                ('hero_description', models.TextField(default='Diseñamos, fabricamos e instalamos soluciones para viviendas, negocios y proyectos en Huancayo.', verbose_name='descripción principal')),
                ('history', models.TextField(blank=True, help_text='La historia definitiva se completará cuando se valide el origen y evolución de MS Electrical.', verbose_name='historia de la empresa')),
                ('founded_year', models.PositiveSmallIntegerField(default=2023, verbose_name='año de inicio')),
                ('whatsapp', models.CharField(default='51921127836', help_text='Ejemplo para Perú: 51921127836.', max_length=15, validators=[django.core.validators.RegexValidator(message='El WhatsApp debe contener solamente números e incluir el código de país. Ejemplo: 51921127836.', regex='^\\d{9,15}$')], verbose_name='WhatsApp con código de país')),
                ('email', models.EmailField(default='pooldigoms18@gmail.com', max_length=254, verbose_name='correo electrónico')),
                ('business_hours', models.CharField(default='8:00 a. m. a 6:00 p. m.', max_length=180, verbose_name='horario de atención')),
                ('response_time', models.CharField(default='Hasta 8 horas dentro del horario de atención.', max_length=180, verbose_name='tiempo estimado de respuesta')),
                ('coverage', models.TextField(default='Huancayo, El Tambo, Chilca y Chupaca.', verbose_name='zona de atención')),
                ('warranty', models.TextField(default='Hasta un año de garantía, según el servicio, los equipos y las condiciones indicadas en la cotización.', verbose_name='condiciones generales de garantía')),
                ('maintenance', models.TextField(default='El seguimiento y mantenimiento se define de acuerdo con el servicio y las condiciones de la cotización.', verbose_name='mantenimiento')),
                ('payment_methods', models.CharField(default='Yape, Plin, transferencia bancaria y Visa.', max_length=250, verbose_name='medios de pago')),
                ('city', models.CharField(default='Huancayo', max_length=100, verbose_name='ciudad')),
                ('region', models.CharField(default='Junín', max_length=100, verbose_name='región')),
                ('country', models.CharField(default='Perú', max_length=100, verbose_name='país')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/MSElectricaPeru', verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/@superpool18', verbose_name='YouTube')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('is_active', models.BooleanField(default=True, verbose_name='información activa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'información de la empresa',
                'verbose_name_plural': 'información de la empresa',
            },
        ),
    ]
