# Generated by Django 5.2.16 on 2026-07-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='enlace de Google Maps'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='código postal'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='public_address',
            field=models.CharField(blank=True, help_text='Completar únicamente si esta dirección puede mostrarse públicamente a los clientes.', max_length=255, verbose_name='dirección pública'),
        ),
    ]
