# Generated by Django 5.2.16 on 2026-07-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyprofile_google_maps_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='pregunta')),
                ('answer', models.TextField(verbose_name='respuesta')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='orden de visualización')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='mostrar en la portada')),
                ('is_active', models.BooleanField(default=True, verbose_name='publicada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'pregunta frecuente',
                'verbose_name_plural': 'preguntas frecuentes',
                'ordering': ('display_order', 'question'),
            },
        ),
    ]
