# Generated by Django 5.2.16 on 2026-07-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_globalfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo principal utilizado en la cabecera y el pie de página del sitio.', upload_to='company/branding/', verbose_name='logo de la empresa'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo_alt_text',
            field=models.CharField(blank=True, default='Logo de MS Electrical', help_text='Descripción breve del logo para accesibilidad.', max_length=150, verbose_name='texto alternativo del logo'),
        ),
    ]
