"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yr@s^qkn13_hl4v*^-af=x4^(-0qfksq@*e+j!6p!hl2$sx5os'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",

    "anymail",
    # Aplicaciones propias de MS Electrical.
    "apps.core.apps.CoreConfig",
    "apps.services.apps.ServicesConfig",
    "apps.portfolio.apps.PortfolioConfig",
    "apps.quotes.apps.QuotesConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# Configuración de plantillas HTML.
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                 "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                 # Datos generales de MS Electrical.
                 "apps.core.context_processors.company_profile",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"
# Archivos cargados desde el panel o formularios.
MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media" 
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ============================================================
# Configuración de correo electrónico
# ============================================================

EMAIL_BACKEND = os.getenv(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)

EMAIL_HOST = os.getenv(
    "DJANGO_EMAIL_HOST",
    "",
)

EMAIL_PORT = int(
    os.getenv(
        "DJANGO_EMAIL_PORT",
        "587",
    )
)

EMAIL_USE_TLS = (
    os.getenv(
        "DJANGO_EMAIL_USE_TLS",
        "True",
    ).lower()
    in (
        "true",
        "1",
        "yes",
    )
)

EMAIL_HOST_USER = os.getenv(
    "DJANGO_EMAIL_HOST_USER",
    "",
)
# ============================================================
# Brevo API mediante Django Anymail
# ============================================================

ANYMAIL = {
    "BREVO_API_KEY": os.getenv(
        "BREVO_API_KEY",
        "",
    ),
}

EMAIL_HOST_PASSWORD = os.getenv(
    "DJANGO_EMAIL_HOST_PASSWORD",
    "",
)

DEFAULT_FROM_EMAIL = os.getenv(
    "DJANGO_DEFAULT_FROM_EMAIL",
    "MS Electrical <no-reply@localhost>",
)

SERVER_EMAIL = DEFAULT_FROM_EMAIL


# Correos que reciben las nuevas solicitudes.
COMPANY_NOTIFICATION_EMAILS = [
    email.strip()
    for email in os.getenv(
        "MS_ELECTRICAL_NOTIFICATION_EMAILS",
        "pooldigoms18@gmail.com",
    ).split(",")
    if email.strip()
]
# ============================================================
# Configuración general del sitio y SEO
# ============================================================

SITE_URL = (
    os.getenv(
        "DJANGO_SITE_URL",
        "",
    )
    .strip()
    .rstrip("/")
)
# ============================================================
# Verificación de servicios para buscadores
# ============================================================

GOOGLE_SITE_VERIFICATION = os.getenv(
    "GOOGLE_SITE_VERIFICATION",
    "",
).strip()
# ============================================================
# Seguridad y límites de solicitudes
# ============================================================

# Los archivos superiores a 1 MB pasan a almacenamiento
# temporal en disco durante la recepción de la solicitud.
FILE_UPLOAD_MAX_MEMORY_SIZE = (
    1 * 1024 * 1024
)

# Limita los datos normales del formulario.
# Los archivos cargados se gestionan separadamente.
DATA_UPLOAD_MAX_MEMORY_SIZE = (
    5 * 1024 * 1024
)

# Evita solicitudes con cantidades anormales de campos.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 500

# El formulario público permite cinco fotografías.
# Este límite global deja margen para el administrador.
DATA_UPLOAD_MAX_NUMBER_FILES = 10


# ============================================================
# Protección del formulario de cotización
# ============================================================

QUOTE_SUBMISSION_COOLDOWN_SECONDS = int(
    os.getenv(
        "QUOTE_SUBMISSION_COOLDOWN_SECONDS",
        "30",
    )
)


# ============================================================
# Vista personalizada para errores CSRF
# ============================================================

CSRF_FAILURE_VIEW = (
    "apps.core.error_views.csrf_failure"
)