# Generated by Django 5.2.16 on 2026-07-15 04:03

import apps.quotes.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_servicebenefit_servicefaq_servicefeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador público')),
                ('reference_code', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='código de solicitud')),
                ('full_name', models.CharField(max_length=180, verbose_name='nombre completo')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Ingresa un número válido usando solamente números, espacios, guiones y, opcionalmente, el símbolo +.', regex='^\\+?[0-9\\s-]{7,20}$')], verbose_name='teléfono o WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('preferred_contact', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Llamada telefónica'), ('email', 'Correo electrónico')], default='whatsapp', max_length=20, verbose_name='medio de contacto preferido')),
                ('preferred_time', models.CharField(choices=[('morning', 'Mañana'), ('afternoon', 'Tarde'), ('any', 'Cualquier horario')], default='any', max_length=20, verbose_name='horario preferido')),
                ('other_service', models.CharField(blank=True, max_length=180, verbose_name='otro servicio o necesidad')),
                ('project_type', models.CharField(choices=[('residential', 'Vivienda'), ('commercial', 'Negocio o comercio'), ('institutional', 'Institución'), ('industrial', 'Industrial'), ('other', 'Otro')], default='residential', max_length=30, verbose_name='tipo de proyecto')),
                ('district', models.CharField(max_length=160, verbose_name='distrito o ubicación')),
                ('address_reference', models.CharField(blank=True, max_length=250, verbose_name='referencia de la ubicación')),
                ('budget_range', models.CharField(blank=True, choices=[('under_1000', 'Menos de S/ 1,000'), ('1000_3000', 'S/ 1,000 a S/ 3,000'), ('3000_7000', 'S/ 3,000 a S/ 7,000'), ('over_7000', 'Más de S/ 7,000'), ('undefined', 'Aún no lo he definido')], max_length=30, verbose_name='presupuesto referencial')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='fecha deseada para el trabajo')),
                ('description', models.TextField(help_text='Describe las medidas aproximadas, el problema actual y el resultado que deseas obtener.', verbose_name='descripción del proyecto')),
                ('privacy_consent', models.BooleanField(default=False, verbose_name='aceptación del uso de datos')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('contacted', 'Cliente contactado'), ('evaluating', 'En evaluación'), ('quoted', 'Cotización enviada'), ('approved', 'Aprobada'), ('closed', 'Finalizada'), ('rejected', 'No concretada')], default='new', max_length=20, verbose_name='estado de la solicitud')),
                ('internal_notes', models.TextField(blank=True, help_text='Este contenido solo será visible para los administradores.', verbose_name='notas internas')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='página de origen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de recepción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='services.service', verbose_name='servicio solicitado')),
            ],
            options={
                'verbose_name': 'solicitud de cotización',
                'verbose_name_plural': 'solicitudes de cotización',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.quotes.models.quote_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.quotes.models.validate_image_size], verbose_name='fotografía')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='descripción de la fotografía')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotes.quoterequest', verbose_name='solicitud')),
            ],
            options={
                'verbose_name': 'fotografía adjunta',
                'verbose_name_plural': 'fotografías adjuntas',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
