# Generated by Django 5.2.16 on 2026-07-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='admin_notification_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='notificación interna enviada'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='customer_confirmation_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='confirmación enviada al cliente'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='notification_error',
            field=models.TextField(blank=True, editable=False, verbose_name='último error de notificación'),
        ),
    ]
