# Generated by Django 5.2.16 on 2026-07-14 22:46

import apps.portfolio.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_servicebenefit_servicefaq_servicefeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True, verbose_name='nombre del proyecto')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente a partir del nombre. Ejemplo: automatizacion-porton-residencial.', max_length=200, unique=True, verbose_name='identificador URL')),
                ('project_type', models.CharField(choices=[('residential', 'Residencial'), ('commercial', 'Comercial'), ('institutional', 'Institucional'), ('industrial', 'Industrial'), ('other', 'Otro')], default='residential', max_length=30, verbose_name='tipo de proyecto')),
                ('location', models.CharField(default='Huancayo, Junín', max_length=180, verbose_name='ubicación')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('short_description', models.CharField(help_text='Resumen que aparecerá en las tarjetas del portafolio.', max_length=280, verbose_name='descripción breve')),
                ('introduction', models.TextField(blank=True, help_text='Descripción general del trabajo realizado.', verbose_name='presentación del proyecto')),
                ('challenge', models.TextField(blank=True, help_text='Explica qué necesitaba resolver el cliente.', verbose_name='necesidad o problema inicial')),
                ('solution', models.TextField(blank=True, help_text='Describe el trabajo, los equipos o materiales utilizados.', verbose_name='solución ejecutada')),
                ('result', models.TextField(blank=True, help_text='Explica los beneficios o mejoras logradas.', verbose_name='resultado obtenido')),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.portfolio.models.project_cover_upload_path, verbose_name='imagen principal')),
                ('cover_alt_text', models.CharField(blank=True, help_text='Describe lo que aparece en la imagen principal.', max_length=180, verbose_name='texto alternativo de la portada')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Los números menores aparecen primero.', verbose_name='orden de presentación')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mostrar como proyecto destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='proyecto publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('services', models.ManyToManyField(blank=True, related_name='projects', to='services.service', verbose_name='servicios realizados')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ('display_order', '-completion_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.portfolio.models.project_gallery_upload_path, verbose_name='archivo de imagen')),
                ('alt_text', models.CharField(help_text='Describe brevemente lo que aparece en la fotografía.', max_length=180, verbose_name='texto alternativo')),
                ('caption', models.CharField(blank=True, max_length=220, verbose_name='descripción visible')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden de presentación')),
                ('is_active', models.BooleanField(default=True, verbose_name='imagen visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'imagen del proyecto',
                'verbose_name_plural': 'imágenes del proyecto',
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
